### ISSUE TITLE
Use bruteforce-rs

### ISSUE THREAD

**Issue by deeprobin** [CCBlueX/rcon_bruteforcer#1]
You could use [bruteforce-rs](https://crates.io/crates/bruteforce/). That's a very fast string generator in rust, which generates strings by your defined charset.

**Comment by kawaiinekololis** [comment]
Looks good. I'll add it in the future.

**Comment by deeprobin** [comment]
okay

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/rcon_bruteforcer/commit/fdafbc0c6f2ed76397127b8cd50e569ab071ed75
