### ISSUE TITLE
add a disclaimer

### ISSUE THREAD

**Issue by ENDER1355** [CCBlueX/rcon_bruteforcer#7]
we know in most countries like us, its illegal to Bruteforce except that you have permission

also add a warning that the app can eat too much space since its a brute force app

**Comment by 1zun4** [comment]
"we know in most countries like us, its illegal to Bruteforce except that you have permission"
There is already a reminder. 

"can eat too much space"
No. You are wrong. It doesn't create any files or use space. Memory usage should be very low. It mostly depends on cpu usage.
